version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: phonenest-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: PhoneNest
      POSTGRES_USER: phonenest_user
      POSTGRES_PASSWORD: superSekret!
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U phonenest_user -d PhoneNest" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: